### ISSUE TITLE
proxy parser

### ISSUE THREAD

**Issue by F-TD5X** [MehdiRtal/MicrosoftRewardsFarmerV2#12]
https://github.com/MehdiRtal/MicrosoftRewardsFarmerV2/blob/d56d055ea5a99cfcac6ead216acc40ace900a263/rewards.py#L23-L25

if dont wanna use any parser, or `LaunchOptions`, please use `[:-1]` rather `[1]`. For what if the proxy doesn't have any auth?

and of couse the `username` and `password`, if no auth, just don't set the key.

**Comment by MehdiRtal** [comment]
What do you think about this solution?
```python
tmp_proxy = None
if proxy:
    tmp_proxy = {
        "server": f"http://{proxy}",
    }
    if "@" in proxy:
        tmp_proxy["server"] = f"http://{proxy.split('@')[1]}"
        tmp_proxy["username"] = proxy.split("@")[0].split(":")[0]
        tmp_proxy["password"] = proxy.split("@")[0].split(":")[1]
self.browser = self.playwright.webkit.launch(
    headless=headless,
    proxy=tmp_proxy
)
```
