### ISSUE TITLE
Check proxy before farm

### ISSUE THREAD

**Issue by bscongluanbui** [MehdiRtal/MicrosoftRewardsFarmerV2#9]
Can you add check proxy before farm. Its will avoid ban account

**Comment by MehdiRtal** [comment]
What do you mean by checking the proxy?

**Comment by bscongluanbui** [comment]
> What do you mean by checking the proxy?

Yes. If proxy not working, the tool skip that account. And you can add log for each account?

**Comment by MehdiRtal** [comment]
That's already the case, but It doesn't log it for now.
